Update and rename check-version-label.yml to validate-release-pr.yml

diff --git a/.github/workflows/validate-release-pr.yml b/.github/workflows/validate-release-pr.yml
--- a/.github/workflows/validate-release-pr.yml
+++ b/.github/workflows/validate-release-pr.yml
@@ -12,8 +12,21 @@ permissions:
 jobs:
   check-label:
     runs-on: ubuntu-latest
-
+    
     steps:
+      - name: Validate source branch
+        env: 
+          SOURCE_BRANCH: ${{ github.event.pull_request.head.ref }}
+        run: | 
+          echo "Source branch: $SOURCE_BRANCH" 
+    
+          if [ "$SOURCE_BRANCH" != "development" ]; then
+            echo "ERROR: Only development branch can be merged into main." 
+            exit 1 
+          fi
+
+          echo "Source branch is valid."
+          
       - name: Validate version label
         env:
           LABELS_JSON: ${{ toJSON(github.event.pull_request.labels.*.name) }}
